# Generated by Django 5.2.17 on 2026-09-14 13:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="internal length"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="internal width"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="internal height"
                    ),
                ),
                ("max_weight", models.DecimalField(decimal_places=3, max_digits=8)),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["shipping_cost", "code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("length", models.DecimalField(decimal_places=2, max_digits=8)),
                ("width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "sku"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "recommended_box_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "selected_box_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("no_solution", "No suitable box"),
                        ],
                        default="no_solution",
                        max_length=20,
                    ),
                ),
                ("evaluation", models.JSONField(blank=True, default=list)),
                (
                    "recommended_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_orders",
                        to="shipping.box",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("product_snapshot", models.JSONField(default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipping.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.product",
                    ),
                ),
            ],
        ),
    ]
